# Generated by Django 5.0.3 on 2024-04-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre  de la tarea: ')),
                ('descripcion', models.TextField(verbose_name='sobre que trata...')),
                ('estado', models.CharField(choices=[(True, 'echo'), (False, 'pendiente')], default=False, max_length=50, verbose_name='Estado: ')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado el dia: ')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
